### ISSUE TITLE
don't return Nil as a Double

### ISSUE THREAD

**Issue by adampingel** [randomforestwhitaker/questions#3]
https://github.com/randomforestwhitaker/questions/blob/df5ab371251d6690faa24f280f5fd266d0a702c5/answer_1.scala#L6

for an empty list, the function should return `Double.NaN`

**Comment by randomforestwhitaker** [comment]
changed Nil to Double.NaN in first resolver function (currently commented out). will keep in mind for Nil case in second resolver function implementation
