### ISSUE TITLE
boolean bad smell

### ISSUE THREAD

**Issue by adampingel** [randomforestwhitaker/questions#4]
https://github.com/randomforestwhitaker/questions/blob/df5ab371251d6690faa24f280f5fd266d0a702c5/answer_1.scala#L15-L20

If you ever find yourself returning `true` or `false`, you're probably not phrasing the function as parsimoniously as you can.  Simplify this expression.

**Comment by randomforestwhitaker** [comment]
simplified to x >= 0. was too eager to apply pattern matching to everything lol
