### ISSUE TITLE
abuse of pattern matching

### ISSUE THREAD

**Issue by adampingel** [randomforestwhitaker/questions#5]
https://github.com/randomforestwhitaker/questions/blob/df5ab371251d6690faa24f280f5fd266d0a702c5/answer_1.scala#L17-L18

Even apart from the previous issue filed about overly complex boolean expression, note that you're not actually using pattern matching here.  Why not just an `if` statement?  [But note that you can get even simpler than that.  Nevertheless, removing the unused pattern matching might help you see the simpler version.]

**Comment by randomforestwhitaker** [comment]
it was so simple, why didn't I see it during the first isNonNegative definition attempt :(
