### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by adampingel** [randomforestwhitaker/questions#7]
https://github.com/randomforestwhitaker/questions/blob/a607680fed8c614a478260e329b4412a57112903/answer_1.scala#L27

You increment `inc` but really need it.

Looks like you may have intended to use it in `average`, that function calls `.length` on it's own.

The only time you read it is in the loop condition `inc <= index`, but isn't that vacuously true? (`inc` will always be less than `index` (which is the same as `xs.length`) for all lists `xs`)

Delete `inc` and the incrementing line.

I may have caught you in the middle of thinking this through, but I can give you a hint that the final version doesn't need this complexity.

**Comment by randomforestwhitaker** [comment]
After much banging of head against wall, finally realized that I could just use takeWhile to satisfy the specs. 🔢

**Comment by adampingel** [comment]
Looking forward to that version...
